### ISSUE TITLE
ModuleNotFoundError: No module named 'down'

### ISSUE THREAD

**Issue by leonheess** [AASHISHAG/deepspeech-german#45]
When I follow all the steps in the READMe and get to `python pre-processing/download_speech_corpus.py --tuda --cv --swc --voxforge --mailabs` I get this error:

```
Traceback (most recent call last):
  File "pre-processing/download_speech_corpus.py", line 6, in <module>
    import audiomate.corpus.io
  File "/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/corpus/io/__init__.py", line 7, in <module>
    from .downloader import ArchiveDownloader
  File "/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/corpus/io/downloader.py", line 7, in <module>
    from audiomate.utils import download
  File "/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/utils/download.py", line 11, in <module>
    from pget.down import Downloader
  File "/deepspeech-german/python-environments/lib/python3.7/site-packages/pget/__init__.py", line 1, in <module>
    from down import Downloader
ModuleNotFoundError: No module named 'down'
```

**Comment by SuperKogito** [comment]
I have the same issue

**Comment by abdallah1989203** [comment]
I am too

**Comment by abdallah1989203** [comment]
this is my solution:
1. cd .. python-environments
2. rm -vrf pget
3. git clone https://github.com/halilozercan/pget
4.cd pget
5.python setup.py install
that works for me! Linux + Mac
