### ISSUE TITLE
create_language_model.sh : HTTP Error 404 (downloading ds native client)

### ISSUE THREAD

**Issue by slinxxy** [AASHISHAG/deepspeech-german#48]
building the language model `create_language_model.sh` ended up in an HTTP 404 Error 

```
Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.9.3.cpu/artifacts/public/native_client.tar.xz ...
Traceback (most recent call last):
  File "DeepSpeech/util/taskcluster.py", line 12, in <module>
    dsu_taskcluster.main()
  File "/var/share/deepspeech-german/DeepSpeech/training/deepspeech_training/util/taskcluster.py", line 128, in main
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
  File "/var/share/deepspeech-german/DeepSpeech/training/deepspeech_training/util/taskcluster.py", line 58, in maybe_download_tc
    _, headers = urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/eike/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Need a hint where to head for a solution

**Comment by slinxxy** [comment]
Finally got my native client from here [https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3](https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3)
